/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreatePlaylistDialog: typeof import('./src/components/Playlist/CreatePlaylistDialog.vue')['default']
    EmptyMusicState: typeof import('./src/components/MusicPage/EmptyMusicState.vue')['default']
    LrcParser: typeof import('./src/components/PlaybackPage/LrcParser.vue')['default']
    MusicFunctionBar: typeof import('./src/components/MusicPage/MusicFunctionBar.vue')['default']
    MusicListItem: typeof import('./src/components/MusicPage/MusicListItem.vue')['default']
    MyHeader: typeof import('./src/components/Header/MyHeader.vue')['default']
    MyNav: typeof import('./src/components/Nav/MyNav.vue')['default']
    MyPlaybackQueue: typeof import('./src/components/PlayerBar/MyPlaybackQueue.vue')['default']
    MyPlayerBar: typeof import('./src/components/PlayerBar/MyPlayerBar.vue')['default']
    NavigationMenu: typeof import('./src/components/Nav/NavigationMenu.vue')['default']
    PlaybackQueueItem: typeof import('./src/components/PlayerBar/PlaybackQueueItem.vue')['default']
    PlaylistCard: typeof import('./src/components/Playlist/PlaylistCard.vue')['default']
    PlaylistLayout: typeof import('./src/components/Playlist/PlaylistLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartMarquee: typeof import('./src/components/Common/SmartMarquee.vue')['default']
    ThemeSwitch: typeof import('./src/components/Nav/ThemeSwitch.vue')['default']
    Toast: typeof import('./src/components/Common/Toast.vue')['default']
    UserPlaylists: typeof import('./src/components/Nav/UserPlaylists.vue')['default']
  }
}
