/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreatePlaylistDialog: typeof import('./src/components/Playlist/CreatePlaylistDialog.vue')['default']
    EmptyMusicState: typeof import('./src/components/MusicPage/EmptyMusicState.vue')['default']
    IconMoon: typeof import('./src/components/Common/icons/IconMoon.vue')['default']
    IconPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IconPhCornersIn: typeof import('~icons/ph/corners-in')['default']
    IconPhCornersOut: typeof import('~icons/ph/corners-out')['default']
    IconPhDotsThree: typeof import('~icons/ph/dots-three')['default']
    IconPhHeart: typeof import('~icons/ph/heart')['default']
    IconPhList: typeof import('~icons/ph/list')['default']
    IconPhListNumbers: typeof import('~icons/ph/list-numbers')['default']
    IconPhMonitor: typeof import('~icons/ph/monitor')['default']
    IconPhMoon: typeof import('~icons/ph/moon')['default']
    IconPhPause: typeof import('~icons/ph/pause')['default']
    IconPhPlay: typeof import('~icons/ph/play')['default']
    IconPhPlus: typeof import('~icons/ph/plus')['default']
    IconPhQueue: typeof import('~icons/ph/queue')['default']
    IconPhRepeat: typeof import('~icons/ph/repeat')['default']
    IconPhShuffle: typeof import('~icons/ph/shuffle')['default']
    IconPhSkipBack: typeof import('~icons/ph/skip-back')['default']
    IconPhSkipForward: typeof import('~icons/ph/skip-forward')['default']
    IconPhSpeakerHigh: typeof import('~icons/ph/speaker-high')['default']
    IconPhSpeakerX: typeof import('~icons/ph/speaker-x')['default']
    IconPhSun: typeof import('~icons/ph/sun')['default']
    IconPhTranslate: typeof import('~icons/ph/translate')['default']
    IconPhTrash: typeof import('~icons/ph/trash')['default']
    IconPhX: typeof import('~icons/ph/x')['default']
    LrcParser: typeof import('./src/components/PlaybackPage/LrcParser.vue')['default']
    MusicFunctionBar: typeof import('./src/components/MusicPage/MusicFunctionBar.vue')['default']
    MusicListItem: typeof import('./src/components/MusicPage/MusicListItem.vue')['default']
    MyHeader: typeof import('./src/components/Header/MyHeader.vue')['default']
    MyIcon: typeof import('./src/components/Common/MyIcon.vue')['default']
    MyNav: typeof import('./src/components/Nav/MyNav.vue')['default']
    MyPlaybackQueue: typeof import('./src/components/PlayerBar/MyPlaybackQueue.vue')['default']
    MyPlayerBar: typeof import('./src/components/PlayerBar/MyPlayerBar.vue')['default']
    NavigationMenu: typeof import('./src/components/Nav/NavigationMenu.vue')['default']
    PlaybackQueueItem: typeof import('./src/components/PlayerBar/PlaybackQueueItem.vue')['default']
    PlaylistCard: typeof import('./src/components/Playlist/PlaylistCard.vue')['default']
    PlaylistLayout: typeof import('./src/components/Playlist/PlaylistLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartMarquee: typeof import('./src/components/Common/SmartMarquee.vue')['default']
    SvgIcon: typeof import('./src/components/Common/SvgIcon.vue')['default']
    ThemeSwitch: typeof import('./src/components/Nav/ThemeSwitch.vue')['default']
    Toast: typeof import('./src/components/Common/Toast.vue')['default']
    UserPlaylists: typeof import('./src/components/Nav/UserPlaylists.vue')['default']
    XhToast: typeof import('./src/components/Common/XhToast.vue')['default']
  }
}
